apiVersion: v1
kind: Pod
metadata:
  name: private-reg
spec:
  containers:
  - name: pet-container
    image: index.docker.io/tortillas/app
  imagePullSecrets:
  - name: dockerhub-registry-credentials