apiVersion: kpack.io/v1alpha1
kind: Builder
metadata:
  name: my-builder
  namespace: default
spec:
  serviceAccount: dockerhub-service-account
  tag: index.docker.io/tortillas/builder1
  stack:
    name: base
    kind: ClusterStack
  store:
    name: default
    kind: ClusterStore
  order:
  - group:
    - id: paketo-buildpacks/java
  - group:
    - id: paketo-buildpacks/java-azure
  - group:
    - id: paketo-buildpacks/graalvm
  - group:
    - id: paketo-buildpacks/nodejs
  - group:
    - id: paketo-buildpacks/dotnet-core
  - group:
    - id: paketo-buildpacks/go
  - group:
    - id: paketo-buildpacks/php
  - group:
    - id: paketo-buildpacks/nginx

  