apiVersion: v1
kind: ServiceAccount
metadata:
  name: dockerhub-service-account
  namespace: default
secrets:
- name: dockerhub-registry-credentials
imagePullSecrets:
- name: dockerhub-registry-credentials